name: poorlex
description: poorlex project
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2+92

environment:
  sdk: ">=3.0.6 <4.0.0"

scripts:
  # freeze 실행
  freezed: "flutter pub run build_runner watch --delete-conflicting-outputs"
  # api로 build
  build:app: flutter build app
  # 안드로이드 배포시 사용, appbundle build
  build:appbundle: flutter build appbundle --release
  # ios 배포시 사용 ipa build
  build:ipa: flutter build ipa
  # ios, android 동시 배포시 사용
  build:prod: "rps build:ipa && rps build:appbundle"
  # 캐시 정리 후 다시 build
  rebuild: flutter clean && flutter pub cache clean && flutter pub get && flutter build apk && flutter build ios
  # ios pod 재설치
  ios:pod:restored: cd ios && rm -rf Podfile.lock && pod install --repo-update && flutter clean && flutter pub get

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  sign_in_with_apple: ^5.0.0
  kakao_flutter_sdk: ^1.5.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2
  kakao_flutter_sdk_user: ^1.5.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  webview_flutter: ^4.5.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # https://pub.dev/packages/freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # https://pub.dev/packages/rps
  rps: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/coin.png
    - assets/poorlex.png
    - assets/img_main_login.png
    - assets/pattern.png
    - assets/app_bar/
    - assets/budget_page/
    - assets/main_page/
    - assets/my_page/
    - assets/ranking/
    - assets/battle_page/
    - assets/sample/
    - assets/my_page/
    - assets/budget_page/
    - assets/goal/
    - assets/login/
    - assets/icons/
    - assets/level/
    - assets/level/profile/

  fonts:
    - family: NeoDunggeunmoPro-Regular
      fonts:
        - asset: assets/font/NeoDunggeunmoPro-Regular.ttf

    - family: appleSDGothicNeo
      fonts:
        - asset: assets/font/AppleSDGothicNeoUL.ttf
          weight: 200
        - asset: assets/font/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: assets/font/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: assets/font/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: assets/font/AppleSDGothicNeoSB.ttf
          weight: 600
        - asset: assets/font/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: assets/font/AppleSDGothicNeoEB.ttf
          weight: 900
